In [1]:
import numpy as np

In [2]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

In [5]:
np.add(1,1)

2

In [7]:
arr = [1,2,3,4,4,4]
np.

array([0, 0, 0, 0, 0, 0])

In [12]:
arr = [1,2,3,4,4,4]
np.all(arr)
# true beacause of array does not contains zero(value)

True

In [11]:
arr2 = [1,2,32,4,5,0]
np.all(arr2)

False

In [15]:
# to detect any of the element is non zero 
arr = [0,0,0,0,0,0]
np.any(arr)

False

In [16]:
arr = [2,0,0,0,0,0]
np.any(arr)

True

In [29]:
# Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
a = np.array([1, 0, np.nan, np.inf,2])
np.isfinite(a)

array([ True,  True, False, False,  True])

In [25]:
#Write a NumPy program to test element-wise for NaN of a given array.
arr = [1,0,np.nan,np.inf,2]
np.isnan(np.array(arr))

array([False, False,  True, False, False])

In [31]:
#is scalar,is complex,is real check
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))


Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [32]:
print(1.00001e10)

10000100000.0


In [34]:
print(1e-8)

1e-08


In [44]:
#element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays
x = np.array([1,2,3,4,5,6,7,])
#y = np.array([1,3,3,4,6,2,3,])
y = np.array([1,2,3,4,5,6,7,])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))
print(np.equal(x,y))
print(np.allclose(x,y))


[False False False False False False False]
[ True  True  True  True  True  True  True]
[False False False False False False False]
[ True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True]
True


In [55]:
# size of the memory (size * itemsize)occupied by the array.
print(np.array([1, 7, 13, 105,'sdsds']).itemsize)
print(np.array([1, 7, 13, 105]).size)
print(np.array([1, 7, 13, 105]).itemsize)
print(np.array(['sd']).itemsize)

84
4
8
8


In [56]:
# program to create an array of 10 zeros, 10 ones, 10 fives.
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [58]:
#program to create an array of the integers from 30 to 70.
print(np.arange(30,71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [60]:
#program to create an array of all the even integers from 30 to 70
print(np.arange(30,70,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [62]:
#program to create a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
#generate a random number between 0 and 1.
print(np.info(np.random.normal))
print(np.random.normal(0,1,1))

normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is ret

In [ ]:
#18th need to check