In [1]:
import numpy as np


In [2]:
#NumPy program to generate an array of 15 random numbers from a standard normal 
print(np.random.normal(0,1,15))

[-0.19588541  0.78151129 -0.61574297  0.06094587  0.21257477 -0.12004091
  0.24541796  0.88318341 -0.10175072 -0.2629675   1.7733663  -3.16981349
  1.83981705  0.1676589  -0.37736289]


In [4]:
#NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.
print('normal array from 15 to 55')
print(np.arange(15,55))
print('without first and last element')
print(np.arange(15,55)[1:-1])


normal array from 15 to 55
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
without first and last element
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [8]:
#NumPy program to create a 3X4 array
a = np.arange(10,22).reshape((3,4))
print(a)
# nditer for ndimentional array
for x in np.nditer(a):
    print(x,end=" ")

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

In [13]:
# nditer other examples
a = [(1,2),(3,'sdsd'),(232,'323'),('dsd',3)]
for i in np.nditer(a):
    print(i,end=' ')

(array(1), array('3', dtype='<U21'), array('232', dtype='<U21'), array('dsd', dtype='<U3')) (array(2), array('sdsd', dtype='<U21'), array('323', dtype='<U21'), array('3', dtype='<U3')) 

In [16]:
# evenly distributed 
v = np.linspace(10,49,5)
print(v)
print(np.linspace(10,49,5,retstep=True))

[10.   19.75 29.5  39.25 49.  ]
(array([10.  , 19.75, 29.5 , 39.25, 49.  ]), 9.75)


In [22]:
#NumPy program to create a vector with values ​​from 0 to 20 and change the sign of the numbers in the range from 9 to 15
a= np.arange(20)
a[(a>=9)&(a<=15)] *= -1
print(a)

# to print higher value of 9 
print(a[(a>=9)])

# print lower values of 9
print(a[(a<=9)])


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]
[16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15]


In [26]:
#Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
a = np.random.randint(0,11,5)
print(a)
print(help(np.random.randint))

[1 4 7 6 3]
Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
        If array-like, must contain integer values
    size : int or tuple of ints, optional
        Out

In [28]:
#Write a NumPy program to multiply the values ​​of two given vectors.
x= np.random.randint(1,22,4)
y= np.random.randint(1,33,4)
print(x)
print(y)
print('----------------')
print(x*y)

[ 3  5 14 15]
[17 17  5 22]
----------------
[ 51  85  70 330]


In [32]:
#Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21
arr = np.arange(10,22).reshape(3,4)
print(arr)
# to find the number of rows and columns 
print(arr.shape)
print('row,column')

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)
row,column


In [35]:
print(np.eye(5))
print(np.eye(4,6)+np.eye(4,6))
print(np.eye(5,k=-2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[2. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [39]:
# matrix 10*10 with number in which the elements on the borders will be equal to 1, and inside 0.
arr = np.ones((10,10))
print(arr)
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:
#Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5. 
arr = np.zeros((5,5))
print(arr)
print(np.eye(5))
print(np.diag([1,2,3,4,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [44]:
#Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. 
arr = np.zeros((4,4))
print(arr)
arr[::2,1::2]=1
arr[1::2,::2]=2
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 1.]
 [2. 0. 2. 0.]
 [0. 1. 0. 1.]
 [2. 0. 2. 0.]]


In [45]:
#to check 31th problem



In [ ]:
#https://www.w3resource.com/python-exercises/numpy/basic/index.php#EDITOR

In [ ]:
#link is upper